[book]
title = "Homelab Setup Documentation"
description = "A comprehensive guide for setting up a secure homelab infrastructure for Data Engineer"
authors = ["leminkhoa"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/leminkhoa/proxmox-homelab-docs"
no-section-label = true
smart-punctuation = true


[output.html.fold]
enable = true
level = 1