[book]
title = "Homelab Setup Documentation"
authors = ["leminkhoa"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/leminkhoa/homelab"
no-section-label = true
smart-punctuation = true


[output.html.fold]
enable = true
level = 1